sys:
  version: 0.0.1

server:
  port: "${SERVER_PORT:8080}"
  servlet:
    context-path: /api

swagger:
  enable: "${SWAGGER_SHOW:true}"
  host: "${SWAGGER_HOST:}"
  base-url: "${SWAGGER_BASE_URL:}"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jackson:
  serialization:
    write-dates-as-timestamps: true

upload:
  maxSize: 20MB
  root: "${STORAGE_ROOT:data/}"

auth:
  secret: "${AUTH_SECRET:123456}"
  token-expire: "${TOEKN_EXPIRE_DAY:30}"

spring:
  profiles:
    active: "${SPRING_ACTIVE_PROFILE:dev}"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL:jdbc:postgresql://localhost:5432/taiko}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"
