sys:
  version: 0.0.1

server:
  port: "${SERVER_PORT:8080}"
  servlet:
    context-path: /api

swagger:
  enable: "${SWAGGER_SHOW:true}"
  base-url: "${SWAGGER_BASE_URL:}"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jackson:
  serialization:
    write-dates-as-timestamps: true

spring:
  profiles:
    active: "${SPRING_ACTIVE_PROFILE:dev}"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL:jdbc:postgresql://localhost:5432/taiko}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"
