sys:
  version: 0.0.1

server:
  port: "${SERVER_PORT:8080}"
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL:jdbc:postgresql://localhost:5432/taiko}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"
