export var Assets = {
    audio: {
        balloon: '/assets/audio/balloon.wav',
        cancel: '/assets/audio/cancel.wav',
        countup: '/assets/audio/countup.wav',
        crown: '/assets/audio/crown.wav',
        do: '/assets/audio/do.wav',
        game_clear: '/assets/audio/game-clear.wav',
        game_fail: '/assets/audio/game-fail.wav',
        ka: '/assets/audio/ka.wav',
        pause: '/assets/audio/pause.wav',
    },
    font: {
        kozuka: '/assets/font/Kozuka.otf',
        tnt: '/assets/font/TnT.ttf',
    },
    img: {
        bad: '/assets/img/bad.png',
        barline: '/assets/img/barline.png',
        completeness: '/assets/img/completeness.png',
        do: '/assets/img/do.png',
        easy: '/assets/img/easy.png',
        extra: '/assets/img/extra.png',
        extreme: '/assets/img/extreme.png',
        game_base: '/assets/img/game-base.png',
        good: '/assets/img/good.png',
        hard: '/assets/img/hard.png',
        ka: '/assets/img/ka.png',
        key: '/assets/img/key.png',
        normal: '/assets/img/normal.png',
        ok: '/assets/img/ok.png',
        screen_bg: '/assets/img/screen-bg.png',
    },
};